[tool.poetry]
name = "fpsql-source"
version = "0.1.0"
description = "Source"
authors = ["Firepup Sixfifty <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10.11"
black = "^24.3.0"

[tool.black]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
